export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS";
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL";
export const EDIT_USER_ACCOUNT_SUCCESS = "EDIT_USER_ACCOUNT_SUCCESS";
export const EDIT_USER_ACCOUNT_FAIL = "EDIT_USER_ACCOUNT_FAIL";

export const CHANGE_ENABLED_USER_ACCOUNT_SUCCESS =
  "CHANGE_ENABLED_USER_ACCOUNT_SUCCESS";
export const CHANGE_ENABLED_USER_ACCOUNT_FAIL =
  "CHANGE_ENABLED_USER_ACCOUNT_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const CREATE_VISUAL_PERCEPTION_SUCCESS =
  "CREATE_VISUAL_PERCEPTION_SUCCESS";
export const CREATE_VISUAL_PERCEPTION_FAIL = "CREATE_VISUAL_PERCEPTION_FAIL";
export const EDIT_VISUAL_PERCEPTION_SUCCESS = "EDIT_VISUAL_PERCEPTION_SUCCESS";
export const EDIT_VISUAL_PERCEPTION_FAIL = "EDIT_VISUAL_PERCEPTION_FAIL";

export const DELETE_VISUAL_PERCEPTION_SUCCESS =
  "DELETE_VISUAL_PERCEPTION_SUCCESS";
export const DELETE_VISUAL_PERCEPTION_FAIL = "DELETE_VISUAL_PERCEPTION_FAIL";

export const CREATE_VISUAL_RECEPTION_SUCCESS =
  "CREATE_VISUAL_RECEPTION_SUCCESS";
export const CREATE_VISUAL_RECEPTION_FAIL = "CREATE_VISUAL_RECEPTION_FAIL";
export const EDIT_VISUAL_RECEPTION_SUCCESS = "EDIT_VISUAL_RECEPTION_SUCCESS";
export const EDIT_VISUAL_RECEPTION_FAIL = "EDIT_VISUAL_RECEPTION_FAIL";
export const DELETE_VISUAL_RECEPTION_SUCCESS =
  "DELETE_VISUAL_RECEPTION_SUCCESS";
export const DELETE_VISUAL_RECEPTION_FAIL = "DELETE_VISUAL_RECEPTION_FAIL";

export const CREATE_VISUAL_PRODUCTION_SUCCESS =
  "CREATE_VISUAL_PRODUCTION_SUCCESS";
export const CREATE_VISUAL_PRODUCTION_FAIL = "CREATE_VISUAL_PRODUCTION_FAIL";

export const EDIT_VISUAL_PRODUCTION_SUCCESS = "EDIT_VISUAL_PRODUCTION_SUCCESS";
export const EDIT_VISUAL_PRODUCTION_FAIL = "EDIT_VISUAL_PRODUCTION_FAIL";
export const DELETE_VISUAL_PRODUCTION_SUCCESS =
  "DELETE_VISUAL_PRODUCTION_SUCCESS";
export const DELETE_VISUAL_PRODUCTION_FAIL = "DELETE_VISUAL_PRODUCTION_FAIL";

export const FETCH_VISUAL_PERCEPTION_TASKS_SUCCESS =
  "FETCH_VISUAL_PERCEPTION_TASKS_SUCCESS";
export const FETCH_VISUAL_PERCEPTION_TASKS_FAIL =
  "FETCH_VISUAL_PERCEPTION_TASKS_FAIL";

export const FETCH_ALL_VISUAL_PERCEPTION_TASKS_SUCCESS =
  "FETCH_ALL_VISUAL_PERCEPTION_TASKS_SUCCESS";
export const FETCH_ALL_VISUAL_PERCEPTION_TASKS_FAIL =
  "FETCH_ALL_VISUAL_PERCEPTION_TASKS_FAIL";

export const FETCH_ALL_VISUAL_PRODUCTION_TASKS_SUCCESS =
  "FETCH_ALL_VISUAL_PRODUCTION_TASKS_SUCCESS";
export const FETCH_ALL_VISUAL_PRODUCTION_TASKS_FAIL =
  "FETCH_ALL_VISUAL_PRODUCTION_TASKS_FAIL";
export const FETCH_ALL_VISUAL_RECEPTION_TASKS_SUCCESS =
  "FETCH_ALL_VISUAL_RECEPTION_TASKS_SUCCESS";
export const FETCH_ALL_VISUAL_RECEPTION_TASKS_FAIL =
  "FETCH_ALL_VISUAL_RECEPTION_TASKS_FAIL";

export const FETCH_VISUAL_RECEPTION_TASKS_SUCCESS =
  "FETCH_VISUAL_RECEPTION_TASKS_SUCCESS";
export const FETCH_VISUAL_RECEPTION_TASKS_FAIL =
  "FETCH_VISUAL_RECEPTION_TASKS_FAIL";

export const FETCH_VISUAL_PRODUCTION_TASKS_SUCCESS =
  "FETCH_VISUAL_PRODUCTION_TASKS_SUCCESS";
export const FETCH_VISUAL_PRODUCTION_TASKS_FAIL =
  "FETCH_VISUAL_PRODUCTION_TASKS_FAIL";

export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";
export const CREATE_TEST_FAIL = "CREATE_TEST_FAIL";

export const FETCH_ALL_TESTS_SUCCESS = "FETCH_ALL_TESTS_SUCCESS";
export const FETCH_ALL_TESTS_FAIL = "FETCH_ALL_TESTS_FAIL";
